# Generated by Django 5.2.15 on 2026-07-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryClickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_analytics', to='urls.shorturl')),
            ],
            options={
                'indexes': [models.Index(fields=['short_url', 'date', 'country'], name='analytics_c_short_u_4d549a_idx')],
                'unique_together': {('short_url', 'date', 'country')},
            },
        ),
        migrations.CreateModel(
            name='DailyClickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='urls.shorturl')),
            ],
            options={
                'indexes': [models.Index(fields=['short_url', 'date'], name='analytics_d_short_u_159608_idx')],
                'unique_together': {('short_url', 'date')},
            },
        ),
    ]
